# Generated by Django 2.0.12 on 2019-12-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SellerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=20, unique=True, verbose_name='seller_name')),
                ('seller_password', models.CharField(max_length=40, verbose_name='seller_password')),
                ('seller_email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('seller_phone', models.CharField(default='', max_length=11, unique=True, verbose_name='seller_phone_number')),
                ('seller_payment_account', models.CharField(default='', max_length=20, unique=True, verbose_name='seller_payment_account')),
            ],
            options={
                'verbose_name': 'seller_info',
                'verbose_name_plural': 'seller_info',
            },
        ),
    ]
